version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.0.0'
      - run:
          name: install-npm
          command: npm ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
      - run:
          name: test-e2e
          command: npm run test:e2e:ci
          environment:
            NO_SANDBOX: true
      - run:
          name: code-coverage
          command: npm run test:coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
